# Generated by Django 4.2.30 on 2026-05-22 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendeur', 'Vendeur'), ('acheteur', 'Acheteur')], default='acheteur', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='profils/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
            },
        ),
    ]
